// Code generated by
// /Users/jatorre/go/pkg/mod/github.com/apache/arrow-adbc/go/adbc@v1.9.0/pkg/_tmpl/utils.h.tmpl.
// DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include "../../drivermgr/arrow-adbc/adbc.h"
#include <stdlib.h>

struct AdbcError *OracleErrorFromArrayStream(struct ArrowArrayStream *,
                                             AdbcStatusCode *);
AdbcStatusCode OracleDatabaseGetOption(struct AdbcDatabase *, const char *,
                                       char *, size_t *, struct AdbcError *);
AdbcStatusCode OracleDatabaseGetOptionBytes(struct AdbcDatabase *, const char *,
                                            uint8_t *, size_t *,
                                            struct AdbcError *);
AdbcStatusCode OracleDatabaseGetOptionDouble(struct AdbcDatabase *,
                                             const char *, double *,
                                             struct AdbcError *);
AdbcStatusCode OracleDatabaseGetOptionInt(struct AdbcDatabase *, const char *,
                                          int64_t *, struct AdbcError *);
AdbcStatusCode OracleDatabaseInit(struct AdbcDatabase *db,
                                  struct AdbcError *err);
AdbcStatusCode OracleDatabaseNew(struct AdbcDatabase *db,
                                 struct AdbcError *err);
AdbcStatusCode OracleDatabaseRelease(struct AdbcDatabase *db,
                                     struct AdbcError *err);
AdbcStatusCode OracleDatabaseSetOption(struct AdbcDatabase *db, const char *key,
                                       const char *value,
                                       struct AdbcError *err);
AdbcStatusCode OracleDatabaseSetOptionBytes(struct AdbcDatabase *, const char *,
                                            const uint8_t *, size_t,
                                            struct AdbcError *);
AdbcStatusCode OracleDatabaseSetOptionDouble(struct AdbcDatabase *,
                                             const char *, double,
                                             struct AdbcError *);
AdbcStatusCode OracleDatabaseSetOptionInt(struct AdbcDatabase *, const char *,
                                          int64_t, struct AdbcError *);

AdbcStatusCode OracleConnectionCancel(struct AdbcConnection *,
                                      struct AdbcError *);
AdbcStatusCode OracleConnectionCommit(struct AdbcConnection *cnxn,
                                      struct AdbcError *err);
AdbcStatusCode OracleConnectionGetInfo(struct AdbcConnection *cnxn,
                                       const uint32_t *codes, size_t len,
                                       struct ArrowArrayStream *out,
                                       struct AdbcError *err);
AdbcStatusCode
OracleConnectionGetObjects(struct AdbcConnection *cnxn, int depth,
                           const char *catalog, const char *dbSchema,
                           const char *tableName, const char **tableType,
                           const char *columnName, struct ArrowArrayStream *out,
                           struct AdbcError *err);
AdbcStatusCode OracleConnectionGetOption(struct AdbcConnection *, const char *,
                                         char *, size_t *, struct AdbcError *);
AdbcStatusCode OracleConnectionGetOptionBytes(struct AdbcConnection *,
                                              const char *, uint8_t *, size_t *,
                                              struct AdbcError *);
AdbcStatusCode OracleConnectionGetOptionDouble(struct AdbcConnection *,
                                               const char *, double *,
                                               struct AdbcError *);
AdbcStatusCode OracleConnectionGetOptionInt(struct AdbcConnection *,
                                            const char *, int64_t *,
                                            struct AdbcError *);
AdbcStatusCode OracleConnectionGetStatistics(struct AdbcConnection *,
                                             const char *, const char *,
                                             const char *, char,
                                             struct ArrowArrayStream *,
                                             struct AdbcError *);
AdbcStatusCode OracleConnectionGetStatisticNames(struct AdbcConnection *,
                                                 struct ArrowArrayStream *,
                                                 struct AdbcError *);
AdbcStatusCode OracleConnectionGetTableSchema(
    struct AdbcConnection *cnxn, const char *catalog, const char *dbSchema,
    const char *tableName, struct ArrowSchema *schema, struct AdbcError *err);
AdbcStatusCode OracleConnectionGetTableTypes(struct AdbcConnection *cnxn,
                                             struct ArrowArrayStream *out,
                                             struct AdbcError *err);
AdbcStatusCode OracleConnectionInit(struct AdbcConnection *cnxn,
                                    struct AdbcDatabase *db,
                                    struct AdbcError *err);
AdbcStatusCode OracleConnectionNew(struct AdbcConnection *cnxn,
                                   struct AdbcError *err);
AdbcStatusCode OracleConnectionReadPartition(struct AdbcConnection *cnxn,
                                             const uint8_t *serialized,
                                             size_t serializedLen,
                                             struct ArrowArrayStream *out,
                                             struct AdbcError *err);
AdbcStatusCode OracleConnectionRelease(struct AdbcConnection *cnxn,
                                       struct AdbcError *err);
AdbcStatusCode OracleConnectionRollback(struct AdbcConnection *cnxn,
                                        struct AdbcError *err);
AdbcStatusCode OracleConnectionSetOption(struct AdbcConnection *cnxn,
                                         const char *key, const char *val,
                                         struct AdbcError *err);
AdbcStatusCode OracleConnectionSetOptionBytes(struct AdbcConnection *,
                                              const char *, const uint8_t *,
                                              size_t, struct AdbcError *);
AdbcStatusCode OracleConnectionSetOptionDouble(struct AdbcConnection *,
                                               const char *, double,
                                               struct AdbcError *);
AdbcStatusCode OracleConnectionSetOptionInt(struct AdbcConnection *,
                                            const char *, int64_t,
                                            struct AdbcError *);

AdbcStatusCode OracleStatementBind(struct AdbcStatement *stmt,
                                   struct ArrowArray *values,
                                   struct ArrowSchema *schema,
                                   struct AdbcError *err);
AdbcStatusCode OracleStatementBindStream(struct AdbcStatement *stmt,
                                         struct ArrowArrayStream *stream,
                                         struct AdbcError *err);
AdbcStatusCode OracleStatementCancel(struct AdbcStatement *,
                                     struct AdbcError *);
AdbcStatusCode OracleStatementExecuteQuery(struct AdbcStatement *stmt,
                                           struct ArrowArrayStream *out,
                                           int64_t *affected,
                                           struct AdbcError *err);
AdbcStatusCode
OracleStatementExecutePartitions(struct AdbcStatement *stmt,
                                 struct ArrowSchema *schema,
                                 struct AdbcPartitions *partitions,
                                 int64_t *affected, struct AdbcError *err);
AdbcStatusCode OracleStatementExecutePartitionsTrampoline(
    struct AdbcStatement *stmt, struct ArrowSchema *schema,
    struct AdbcPartitions *partitions, int64_t *affected,
    struct AdbcError *err);
AdbcStatusCode OracleStatementExecuteSchema(struct AdbcStatement *,
                                            struct ArrowSchema *,
                                            struct AdbcError *);
AdbcStatusCode OracleStatementGetOption(struct AdbcStatement *, const char *,
                                        char *, size_t *, struct AdbcError *);
AdbcStatusCode OracleStatementGetOptionBytes(struct AdbcStatement *,
                                             const char *, uint8_t *, size_t *,
                                             struct AdbcError *);
AdbcStatusCode OracleStatementGetOptionDouble(struct AdbcStatement *,
                                              const char *, double *,
                                              struct AdbcError *);
AdbcStatusCode OracleStatementGetOptionInt(struct AdbcStatement *, const char *,
                                           int64_t *, struct AdbcError *);
AdbcStatusCode OracleStatementGetParameterSchema(struct AdbcStatement *stmt,
                                                 struct ArrowSchema *schema,
                                                 struct AdbcError *err);
AdbcStatusCode OracleStatementNew(struct AdbcConnection *cnxn,
                                  struct AdbcStatement *stmt,
                                  struct AdbcError *err);
AdbcStatusCode OracleStatementPrepare(struct AdbcStatement *stmt,
                                      struct AdbcError *err);
AdbcStatusCode OracleStatementRelease(struct AdbcStatement *stmt,
                                      struct AdbcError *err);
AdbcStatusCode OracleStatementSetOption(struct AdbcStatement *stmt,
                                        const char *key, const char *value,
                                        struct AdbcError *err);
AdbcStatusCode OracleStatementSetOptionBytes(struct AdbcStatement *,
                                             const char *, const uint8_t *,
                                             size_t, struct AdbcError *);
AdbcStatusCode OracleStatementSetOptionDouble(struct AdbcStatement *,
                                              const char *, double,
                                              struct AdbcError *);
AdbcStatusCode OracleStatementSetOptionInt(struct AdbcStatement *, const char *,
                                           int64_t, struct AdbcError *);
AdbcStatusCode OracleStatementSetSqlQuery(struct AdbcStatement *stmt,
                                          const char *query,
                                          struct AdbcError *err);
AdbcStatusCode OracleStatementSetSubstraitPlan(struct AdbcStatement *stmt,
                                               const uint8_t *plan,
                                               size_t length,
                                               struct AdbcError *err);

AdbcStatusCode AdbcDriverOracleInit(int version, void *rawDriver,
                                    struct AdbcError *err);

static inline void OracleerrRelease(struct AdbcError *error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void Oracle_release_error(struct AdbcError *error);

struct OracleError {
  char *message;
  char **keys;
  uint8_t **values;
  size_t *lengths;
  int count;
};

void OracleReleaseErrWithDetails(struct AdbcError *error);

int OracleErrorGetDetailCount(const struct AdbcError *error);
struct AdbcErrorDetail OracleErrorGetDetail(const struct AdbcError *error,
                                            int index);

int OracleArrayStreamGetSchemaTrampoline(struct ArrowArrayStream *stream,
                                         struct ArrowSchema *out);
int OracleArrayStreamGetNextTrampoline(struct ArrowArrayStream *stream,
                                       struct ArrowArray *out);
